create table tk_order_entire(
  id int not null auto_increment primary key,
  admin_id int not null default 0 comment '操作者ID',
  customer_id int not null default 0 comment '客户信息ID',
  source_id int not null default 0 comment '渠道来源',
  sales_id int not null default 0 comment '签单销售ID',
  manager_id int not null default 0 comment '区域经理ID',
  sign_date int not null default 0 comment '签约日期',
  wedding_date int not null default 0 comment '举办日期',
  bridegroom char(20) not null default '' comment '新郎姓名',
  bridegroom_mobile char(20) not null default '' comment '新郎电话',
  bride char(20) not null default '' comment '新娘姓名',
  bride_mobile char(20) not null default '' comment '新娘电话',
  is_entire int not null default 0 comment '是否是一站式',
  entire_price decimal(10,2) default '0.0' comment '一站式价格',
  table_amount int not null default 0 comment '桌数',
  table_price decimal(10,2) default '0.0' comment '餐标,每桌的价钱',
  wine_fee decimal(10,2) default '0.0' comment '酒水,酒水费用',
  service_fee decimal(10,2) default '0.0' comment '服务费',
  income_customer_fee decimal(10,2) default '0.0' comment '应收客人费用',
  income_wedding_celebration_admission_fee decimal(10,2) default '0.0' comment '收婚庆进场费',
  income_fee decimal(10,2) default '0.0' comment '收入总额',
  pay_hotel_admission_fee decimal(10,2) default '0.0' comment '付酒店进场费',
  pay_hotel_fee decimal(10,2) default '0.0' comment '应付酒店费用',
  platform_source_fee decimal(10,2) default '0.0' comment '平台渠道费用',
  person_source_fee decimal(10,2) default '0.0' comment '个人渠道费用',
  other_source_fee decimal(10,2) default '0.0' comment '私下来往小费',
  hongsi_settlement_fee decimal(10,2) default '0.0' comment '红丝婚庆结算费',
  wedding_banquet_commission decimal(10,2) default '0.0' comment '婚宴提成',
  wedding_celebration_commission decimal(10,2) default '0.0' comment '婚庆提成',
  total_pay decimal(10,2) default '0.0' comment '支出总额',
  revenue decimal(10,2) default '0.0' comment '营收',
  gross_profit decimal(10,2) default '0.0' comment '毛利',
  end_commission decimal(10,2) default '0.0' comment '最终提成',
  manager_commission decimal(10,2) default '0.0' comment '区域经理提成',
  manager_recommend_commission decimal(10,2) default '0.0' comment '区域经理引流提成',
  create_time int not null default 0,
  update_time int not null default 0,
  remark text
);
